### ISSUE TITLE
roadmap v1

### ISSUE THREAD

**Issue by himself65** [himself65/swc-plugin-react-server#3]
- [x] validate file server/client side
  - [ ] check for the react APIs
- [ ] transform server action
  - [x] client side https://github.com/himself65/react-server/pull/4
  - [ ] server side
	  - [x] top-level server action https://github.com/himself65/react-server/pull/2
	  - [ ]  nested server action
- [ ] usage for waku.gg
- [ ] document
